# 通用配置
spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/redflower?useUnicode=true&amp;characterEncoding=UTF-8&useSSL=false
    username: root
    password: xiaohu2815
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

wx:
  appid: wx67618f9dbb31145d
  secret: 590424b0f1edfe7244d38421fec3b72b
  url: https://api.weixin.qq.com/sns/jscode2session?appid=${wx.appid}&secret=${wx.secret}&grant_type=authorization_code&js_code=


server:
  port: 8080
logging:
  level:
    org.springframework.web: warn
    com.weizhi: warn
  pattern:
    # 格式化
    console: "[%-5level] %d{yyyy-MM-dd HH:mm:ss} - %msg%n"
    # 日志文件名
    file: "[%-5level] %d{yyyy-MM-dd HH:mm:ss} [%thread] %logger{36} - %msg%n"
    # 会在当前路径保存
  file: redflower.log
